### ISSUE TITLE
Can't install 2.1.0 on Python 3.7 Raspberry Pi 4

### ISSUE THREAD

**Issue by gilescoope** [PINTO0309/Tensorflow-bin#19]
It gets stuck on the "Building wheels for scipy" stage.
Firstly if the fortran compiler isn't found it fails. But even after I run
sudo apt-get install gfortran
I get errors

**Comment by PINTO0309** [comment]
If possible, post the full text of all executed commands and error messages. I can't grasp the situation.

**Comment by gilescoope** [comment]
I've got this working now. The problem is that scipy 1.4.1, a requirement for Tensorflow 2.1, doesn't have a prebuilt wheel so has to be built from source.

This has some dependencies, I got it to install using
sudo apt-get install gcc gfortran python-dev libgfortran5 libatlas3-base libatlas-base-dev libopenblas-dev libopenblas-base libblas-dev liblapack-dev cython 
sudo pip3 install pybind11

**Comment by PINTO0309** [comment]
@gilescoope 
Thank you for pointing that out. Closed because it was reflected in the README.
