### ISSUE TITLE
TF-2.3.0-cp38-cp38m-linux_aarch64.whl is not supported wheel

### ISSUE THREAD

**Issue by Etoye** [PINTO0309/Tensorflow-bin#28]
device:  RaspberryPi3 B+
CPU architecture :  aarch64 
OS:  Ubuntu 20.04 64bit
Work you did before the problem occurred:  Clean installation of Ubuntu 20.04
Error message:  tensorflow-2.3.0-cp38-cp38m-linux_aarch64.whl is not a supported wheel on this platform.

Not able to install the wheel due to error above, even if all conditions look correct.

**Comment by Etoye** [comment]
Installed miniconda aarch64 with Python 3.7 and able to run tensorflow-2.3.0rc0-cp37-cp37m-linux_aarch64.whl 
Still not sure what is an issue with 3.8 thought.

**Comment by PINTO0309** [comment]
Please rename the file name and try again.

From
**`tensorflow-2.3.0-cp38-cp38m-linux_aarch64.whl`**
To
**`tensorflow-2.3.0-cp38-none-linux_aarch64.whl`**

**Comment by Etoye** [comment]
Installation started right after the file was renamed, thank you!
