### ISSUE TITLE
Trying to install tensorflow-2.1.0-cp37-cp37m-linux_armv7l_download.sh

### ISSUE THREAD

**Issue by Martin-Stevlik** [PINTO0309/Tensorflow-bin#30]
Hello, 
I have tried to install your tensorflow-bin, but I ran into an error. I installed all the necessary packages and did exactly like in your tutorial. 
![tensorflow_bin_error](https://user-images.githubusercontent.com/72346204/112123600-af3ea780-8bc1-11eb-8c00-4a6113cd5dcb.png)

**Comment by PINTO0309** [comment]
The file you are trying to run is an html file.
