### ISSUE TITLE
Found existing installation: wrapt 1.10.11 (When install tensorflow 2.5

### ISSUE THREAD

**Issue by hanifizzudinrahman** [PINTO0309/Tensorflow-bin#36]
**[Required]** Your device (RaspberryPi3, LaptopPC, or other device name):  Raspberry Pi3
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  i don't know
  
**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  Raspbian
  
**[Required]** Details of the work you did before the problem occurred:  Install tensorflow Lite, with follow this instructure 
![2021-06-20-095951_1440x900_scrot](https://user-images.githubusercontent.com/47806867/122660787-55dd1900-d1ae-11eb-9a5c-c3b7e17b84e6.png)

  
**[Required]** Error message:  Installing collected packages: wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-nightly, h5py, google-pasta, gast, flatbuffers, astunparse, tensorflow
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.10.11
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
![2021-06-20-100359_1440x900_scrot](https://user-images.githubusercontent.com/47806867/122660855-e582c780-d1ae-11eb-9313-c7dfcdf2d408.png)

  
**[Required]** Overview of problems and questions:  How i solve this? because i still can'nt install library tensorflow as this follow
  
![2021-06-20-100300_1440x900_scrot](https://user-images.githubusercontent.com/47806867/122660832-bb310a00-d1ae-11eb-835d-b88f38fbf9df.png)

**Comment by emojifreak** [comment]
`apt-get purge python3-wrapt` **before** installation of TF probably resolves this issue.
