### ISSUE TITLE
Link is invalid

### ISSUE THREAD

**Issue by yuanqinong** [PINTO0309/Tensorflow-bin#38]
Hello, I try the follow command **$ wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh"** to download the TensorFlow but it shows an error 404 to me. Could help me about this issue?

**Comment by PINTO0309** [comment]
It's a problem with your network environment. Unfortunately, there is nothing I can do.
```bash
~$ cd test
~/test$ wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh"
--2021-08-16 20:13:10--  https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 374 [text/plain]
Saving to: ‘tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh’

tensorflow-1.15.0-c 100%[================>]     374  --.-KB/s    in 0s      

2021-08-16 20:13:10 (40.9 MB/s) - ‘tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh’ saved [374/374]

~/test$ ls -l
total 4
-rw-rw-r-- 1 xxxxx xxxxx 374  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
~/test$ sudo chmod +x tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh 
~/test$ ./tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   1263      0 --:--:-- --:--:-- --:--:--  1263
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 63.4M    0 63.4M    0     0  7927k      0 --:--:--  0:00:08 --:--:-- 11.3M
Download finished.
~/test$ ls -l
total 65004
-rwxrwxr-x 1 xxxxx xxxxx      374  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
-rw-rw-r-- 1 xxxxx xxxxx 66556874  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l.whl

```

**Comment by yuanqinong** [comment]
Sorry dude, I inserted the wrong link. I am gonna try to install TensorFlow 2. Cloud you check again with this [link ](url).

**Comment by yuanqinong** [comment]
> It's a problem with your network environment. Unfortunately, there is nothing I can do.
> 
> ```shell
> ~$ cd test
> ~/test$ wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh"
> --2021-08-16 20:13:10--  https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 374 [text/plain]
> Saving to: ‘tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh’
> 
> tensorflow-1.15.0-c 100%[================>]     374  --.-KB/s    in 0s      
> 
> 2021-08-16 20:13:10 (40.9 MB/s) - ‘tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh’ saved [374/374]
> 
> ~/test$ ls -l
> total 4
> -rw-rw-r-- 1 xxxxx xxxxx 374  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
> ~/test$ sudo chmod +x tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh 
> ~/test$ ./tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   408    0   408    0     0   1263      0 --:--:-- --:--:-- --:--:--  1263
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 63.4M    0 63.4M    0     0  7927k      0 --:--:--  0:00:08 --:--:-- 11.3M
> Download finished.
> ~/test$ ls -l
> total 65004
> -rwxrwxr-x 1 xxxxx xxxxx      374  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh
> -rw-rw-r-- 1 xxxxx xxxxx 66556874  8月 16 20:13 tensorflow-1.15.0-cp37-cp37m-linux_armv7l.whl
> ```

Sorry dude, I inserted the wrong link. I am gonna try to install TensorFlow 2. Cloud you check again with this link https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.6.0-cp37-none-linux_armv7l_download.sh .
```
pi@raspberrypi:~ $ wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.6.0-cp37-none-linux_armv7l_download.sh"
--2021-08-16 13:24:22--  https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.6.0-cp37-none-linux_armv7l_download.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-16 13:24:23 ERROR 404: Not Found.
```

**Comment by PINTO0309** [comment]
It's just that it hasn't been built and committed yet.
![Screenshot from 2021-08-16 21-35-49](https://user-images.githubusercontent.com/33194443/129564845-bbaf9978-0581-4072-86ac-7e66cf9b957b.png)
