### ISSUE TITLE
Using tensorflow-2.5.0-cp37-none-linux_armv7l_numpy1200_download.sh downloads .whl with numpy~=1.19.2 in requirements

### ISSUE THREAD

**Issue by EddieTheHead** [PINTO0309/Tensorflow-bin#39]
**[Device]** Your device (RaspberryPi3, LaptopPC, or other device name):  
RaspberryPi4
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  
armv7l
  
**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  
Raspbian GNU/Linux 10 (buster)

**[Required]** Details of the work you did before the problem occurred:  
following: _Example of Python 3.x + Tensorflow v2 series_ except in virtual env and without using sudo with pip3 commands. 

**[Required]** Error message:  
```
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.20.3 which is incompatible.
```

**[Required]** Overview of problems and questions:  
  Following the above section from README will land user with broken tensorflow installation, because .whl file replaces numpy 
1.20.3 installed manualy with numpy 1.19.5. 

```
Installing collected packages: numpy, tensorflow
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
Successfully installed numpy-1.19.5 tensorflow-2.5.0
```
in order to fix this user has to reinstall numpy which produces the misleading pip error message. 

```
$ pip3 install install numpy==1.20.3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting install
  Downloading https://www.piwheels.org/simple/install/install-1.3.4-py3-none-any.whl (3.1 kB)
Collecting numpy==1.20.3
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.20.3-cp37-cp37m-linux_armv7l.whl (11.6 MB)
Installing collected packages: numpy, install
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.20.3 which is incompatible.
```

**Comment by PINTO0309** [comment]
Updated.

- tensorflow-2.5.0-cp37-none-linux_armv7l_numpy1200_download.sh
https://drive.google.com/file/d/1qfAKqNfWWHX0t017twOUAYTzdFa9k3Em/view?usp=sharing
