### ISSUE TITLE
issue on wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.6.0-cp37-none-linux_aarch64_download.sh"

### ISSUE THREAD

**Issue by jinghan713** [PINTO0309/Tensorflow-bin#40]
**[Required]** Your device (RaspberryPi3, LaptopPC, or other device name):  
  RaspberryPi3 B+
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  
  armv7l
**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  
  Raspbian
**[Required]** Details of the work you did before the problem occurred:  
  I tried $ wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.6.0-cp37-none-linux_aarch64_download.sh" but it show error 404 can't find the path
**[Required]** Error message:  
  HTTP request sent, awaiting response... 404 Not Found
**[Required]** Overview of problems and questions:  
  Not sure why the path link can't found

**Comment by PINTO0309** [comment]
wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/main/tensorflow-2.6.0-cp37-none-linux_aarch64_numpy1195_download.sh"

**Comment by jinghan713** [comment]
Hi the access for the tensorflow-2.6.0-cp37-none-linux_aarch64_numpy1195_download.sh is denied unable to proceed . can you open the access? Thanks a lot

**Comment by PINTO0309** [comment]
The aarch64 installer will not work on armv7l operating systems, you will need to download the armv7l files.

**Comment by jinghan713** [comment]
Hi, sorry for disturbing but I faced another issue although I had use the armv7l files but I face issue while running sudo-H pip3 install tensorflow-2.5.0-cp37-none-linux armv7l.whl. I had tried apt.get purge python3-wrapt but I can't run the apt.get command
<img width="528" alt="image" src="https://user-images.githubusercontent.com/76024692/139899198-88d6b4ba-6811-4cfb-9201-e13b416074bd.png">
