### ISSUE TITLE
Dependency issue with tensorflow 2.7 on python 3.9

### ISSUE THREAD

**Issue by dnlmlr** [PINTO0309/Tensorflow-bin#41]
### Details of the work you did before the problem occurred:  
1. Follow the Usage: "*Example of Python 3.x + Tensorflow v2 series*" steps up to the `wget` step
2. From the the wget step on, use the [tensorflow-2.7.0-cp39-none-linux_aarch64_numpy1214_download.sh](https://github.com/PINTO0309/Tensorflow-bin/blob/6e17bcb9a2dba5578d041bf011ff875b4e9d1d28/tensorflow-2.7.0-cp39-none-linux_aarch64_numpy1214_download.sh) script instead
  
### Error message:  
```
ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.21.0 (from tensorflow)
ERROR: No matching distribution found for tensorflow-io-gcs-filesystem>=0.21.0
```
  
### Overview of problems and questions:  
- Tensorflow 2.7 seems to depend on the `tensorflow-io-gcs-filesystem` package
- [That package](https://pypi.org/project/tensorflow-io-gcs-filesystem/#files) doesn't seem to be available for arm versions (`aarch64` and `armv7l`) via pip if I didn't miss something
- Is there way to get around this, maybe by building it manually or including it in the wheel?

**Comment by PINTO0309** [comment]
Updated the file. Please try again.

**Comment by dnlmlr** [comment]
This seems to have worked great. 
The installation completed successfully and a small test program also worked just fine. 

So I assume this was an optional dependency, as you simply removed the dependency from the manifest?

**Comment by PINTO0309** [comment]
Have you checked what TensorFlow I/O is? I don't expect this to be a problem unless you need to access special storage.
- https://github.com/tensorflow/io
![Screenshot 2021-11-18 08:22:09](https://user-images.githubusercontent.com/33194443/142298261-3e83d2b4-9207-42e9-9d1c-c9209e0cb44e.png)

Since the original purpose of wheel was to reason with edge devices, unnecessary garbage packages are not included in the build. 
```bash
$ sudo bazel --host_jvm_args=-Xmx512m build \
--config=monolithic \
--config=noaws \
--config=nohdfs \
--config=nonccl \
--config=v2 \
--local_ram_resources=4096 \
--local_cpu_resources=2 \
--copt=-mfpu=neon-vfpv4 \
--copt=-ftree-vectorize \
--copt=-funsafe-math-optimizations \
--copt=-ftree-loop-vectorize \
--copt=-fomit-frame-pointer \
--copt=-DRASPBERRY_PI \
--host_copt=-DRASPBERRY_PI \
--linkopt=-Wl,-latomic \
--host_linkopt=-Wl,-latomic \
--define=tensorflow_mkldnn_contraction_kernel=0 \
--define=raspberry_pi_with_neon=true \
--define=tflite_pip_with_flex=true \
--define=tflite_with_xnnpack=true \
//tensorflow/tools/pip_package:build_pip_package
```
I think the inclusion of unbuildable tensorflow-io in the dependency is nothing but a bug in TensorFlow.

**Comment by PINTO0309** [comment]
Closed due to lack of progress.

**Comment by PINTO0309** [comment]
- TensorFlow I/O wheel
http://snapshots.linaro.org/ldcg/python/tensorflow-io-manylinux/7/tensorflow-io/
