### ISSUE TITLE
ERROR: tensorflow-2.5.0-cp 37-none-linux_armv71.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by RonakGulati** [PINTO0309/Tensorflow-bin#46]
### Issue Type

Bug

### OS

RaspberryPi OS Buster

### OS architecture

armv7

### Hardware

RaspberryPi4

### Description

When doing pip install tensorflow-2.5.0-cp 37-none-linux_armv71.whl is not a supported wheel on this platform.
getting not a supported wheel on this platform my python version is 3.9.2

### Relevant Log Output

```shell
ERROR: tensorflow-2.5.0-cp 37-none-linux_armv71.whl is not a supported wheel on this platform.
```

**Comment by PINTO0309** [comment]
The .whl with the name you listed in your log does not exist.
- error
```
tensorflow-2.5.0-cp 37-none-linux_armv71.whl
```
- correct
```
tensorflow-2.5.0-cp37-none-linux_armv7l.whl
```

Also, I have not built wheel for Python 3.9. If you really want to install it on a 32bit OS, you can try renaming it from cp37 to cp39. I don't know if it will work correctly or not.

You should ask yourself once if you really need to use the full version of TensorFlow. If you do not need to use the full version of TensorFlow and only need TensorFlowLite, the following wheel is available.

https://github.com/PINTO0309/TensorflowLite-bin/tree/main/2.8.0
