### ISSUE TITLE
Error executing pip3 install tensorflow-2.8.0-cp39-none-linux_aarch64.whl

### ISSUE THREAD

**Issue by davidto098** [PINTO0309/Tensorflow-bin#47]
### Issue Type

Support

### OS

Other

### OS architecture

aarch64

### Hardware

Other

### Description

i have the problem describe in the tittle, when i execute pip3 install tensorflow-2.8.0-cp39-none-linux_aarch64.whl in my raspberry pi 3b +, with this especs 

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
 i got this message in the bash: 
ERROR: Wheel 'tensorflow' located at /home/pi/Project/tensorflow-2.8.0-cp39-none-linux_aarch64.whl is invalid.

please help

i have install this dependencies before execute the command in a virtualenv:
pip list

Package             Version
------------------- -------
h5py                3.1.0
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.0
mock                4.0.3
numpy               1.22.1
pip                 22.0.3
pybind11            2.9.1
setuptools          60.6.0
six                 1.16.0
wheel               0.37.1
 

### Relevant Log Output

```shell
$ pip3 install tensorflow-2.8.0-cp39-none-linux_aarch64.whl

ERROR: Wheel 'tensorflow' located at /home/pi/Project/tensorflow-2.8.0-cp39-none-linux_aarch64.whl is invalid.
```

**Comment by PINTO0309** [comment]
Due to the high volume of download requests from around the world, my Google Drive has reached its download limit. Therefore, the file may not have been downloaded properly. I deleted the files on Google Drive and migrated them to Releases on GitHub, try the following.
```bash
cd Tensorflow-bin
git pull
sudo chmod +x tensorflow-2.8.0-cp38-none-linux_aarch64_numpy1221_download.sh
./tensorflow-2.8.0-cp38-none-linux_aarch64_numpy1221_download.sh
```

**Comment by davidto098** [comment]
I repeated the first procedure and now i get this message from bash , because do directly in the repo clone doesnt work for me, 

I am doing  the instalation in a virtual environment 

sudo pip install tensorflow-2.8.0-cp39-none-linux_aarch64.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./tensorflow-2.8.0-cp39-none-linux_aarch64.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow==2.8.0) (52.0.0)
Collecting keras-preprocessing>=1.1.1
  Using cached https://www.piwheels.org/simple/keras-preprocessing/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.43.0-cp39-cp39-manylinux_2_17_aarch64.whl (50.1 MB)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.8.0) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/lib/python3/dist-packages (from tensorflow==2.8.0) (3.7.4.3)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow==2.8.0) (1.16.0)
Collecting flatbuffers>=1.12
  Using cached https://www.piwheels.org/simple/flatbuffers/flatbuffers-20181003210633-py2.py3-none-any.whl (14 kB)
Collecting gast>=0.2.1
  Downloading https://www.piwheels.org/simple/gast/gast-0.5.3-py3-none-any.whl (19 kB)
Collecting keras<2.9,>=2.8.0rc0
  Using cached keras-2.8.0-py2.py3-none-any.whl (1.4 MB)
Collecting astunparse>=1.6.0
  Using cached https://www.piwheels.org/simple/astunparse/astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting tensorboard<2.9,>=2.8
  Using cached tensorboard-2.8.0-py3-none-any.whl (5.8 MB)
Requirement already satisfied: wrapt>=1.11.0 in /usr/lib/python3/dist-packages (from tensorflow==2.8.0) (1.12.1)
Collecting tf-estimator-nightly==2.8.0.dev2021122109
  Using cached tf_estimator_nightly-2.8.0.dev2021122109-py2.py3-none-any.whl (462 kB)

ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow) (from versions: none)
ERROR: No matching distribution found for tensorflow-io-gcs-filesystem>=0.23.1

**Comment by PINTO0309** [comment]
I see. That went well. Please wait a moment. I'll fix the binary.

**Comment by PINTO0309** [comment]
@davidto098 
I've updated the wheel file. Try to download and install it again.

**Comment by davidto098** [comment]
Thank you, finally I was able to install tensorflow successfully in raspberry pi 3b+, your great

**Comment by jodumagpi** [comment]
Is it possible for older versions?
