### ISSUE TITLE
Ubuntu 22.04 has been released. Are you interested in adaptation?

### ISSUE THREAD

**Issue by shaneZhang** [PINTO0309/Tensorflow-bin#48]
### Issue Type

Feature Request

### OS

Other

### OS architecture

aarch64

### Hardware

Other

### Description

Ubuntu 22.04 has been released. Are you interested in adaptation? it is used python 3.10.

### Relevant Log Output

```shell
no
```

**Comment by PINTO0309** [comment]
There are no plans at this time as there is no point in doing a build until the official repositories implement the internal logic support.
https://github.com/tensorflow/tensorflow/issues/55701

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/Tensorflow-bin/releases/tag/v2.9.0

**Comment by shaneZhang** [comment]
thanks very much!
