### ISSUE TITLE
Error after installing tensorflow

### ISSUE THREAD

**Issue by RatheeshRK** [PINTO0309/Tensorflow-bin#5]
NVIDIA-Drive PX2
  
**[Required]** Details of the work you did before the problem occurred:  
<br> Installed tensorflow, pip list |grep tensorflow shows the correct version
<br> I had set the environment variables:LD_LIBRARY_PATH  as /usr/local/cuda-9.2/lib64
<br>
**[Required]** Error message:  
<br> ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
<br>
<br>
**[Required]** Overview of problems and questions:  
<br>
<br>
<br>

**Comment by PINTO0309** [comment]
As it is displayed in the error message.
The version of CUDA is different.
If you want to use CUDA version 9.2, please build Tensorflow yourself.

**Comment by PINTO0309** [comment]
Close because there is no reply for 2 months or more.
