### ISSUE TITLE
ERROR: tensorflow-2.9.0-cp39-none-linux_aarch64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by AnandJNair** [PINTO0309/Tensorflow-bin#54]
### Issue Type

Bug

### OS

RaspberryPi OS Buster

### OS architecture

aarch64

### Hardware

RaspberryPi4

### Description

I was trying to install tensorflow thats when i came across this issue.  I checked if there was any previously installed tensorflow but it was not there. But after that when i installed tensor flow by giving the pip install tensorflow-2.9.0-cp39-none-linux_aarch64.whl  command it popped an error with tensorflow-2.9.0-cp39-none-linux_aarch64.whl is not a supported wheel on this platform.

### Relevant Log Output

```shell
(env) pi@raspberrypi:~/project $ pip install tensorflow-2.9.0-cp39-none-linux_aarch64.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: tensorflow-2.9.0-cp39-none-linux_aarch64.whl is not a supported wheel on this platform.
```

**Comment by PINTO0309** [comment]
`cp37` only. 

https://github.com/PINTO0309/Tensorflow-bin/tree/main?tab=readme-ov-file#tensorflow-bin

**Python API packages**

|Device|OS|Distribution|Architecture|Python ver|Note|
|:--|:--|:--|:--|:--|:--|
|RaspberryPi3/4|Raspbian/Debian|Buster|armhf / armv7l|3.7.3 / 2.7.16|32bit, glibc2.28|
|RaspberryPi3/4|RaspberryPiOS/Debian|Buster|aarch64 / armv8|3.7.3|64bit, glibc2.28|
